### PR TITLE
About Section Refinements, Footer, along with other minor improvements.

### PR DESCRIPTION
**Pull request by NaveenMaurya749**
A toggleable addition has been materialized, which makes the About Section look less barren in Desktop/Landscape mode. Again, this is toggleable, so Mobile users need not confront a text-wall with considerable mass.
image
image

A short and succinct footer has been added too.
image

There have been other minor improvements too.

### CODE REVIEW

**Comment by mrigankpawagi** [comment]
I'll reiterate some of the feedback: 

1. I will suggest that the content of the 'about' section is sent to the content team before including it on the website. 
2. The footer content should be contained to a maximum width of 1200px (like the navbar and main)
3. The footer looks a bit too _filled_ and wordy. Please explore some alternatives, as we discussed.

**Review by mrigankpawagi — CHANGES_REQUESTED** [review]
I'll reiterate some of the feedback: 

1. I will suggest that the content of the 'about' section is sent to the content team before including it on the website. 
2. The footer content should be contained to a maximum width of 1200px (like the navbar and main)
3. The footer looks a bit too _filled_ and wordy. Please explore some alternatives, as we discussed.

**Comment by NaveenMaurya749** [comment]
Requested changes have been enacted, as depicted here:
image
I think it's time this pull request is closed.

**Comment by NaveenMaurya749** [comment]
The final commit for this pull request has been enacted.
I do not happen to have merge access. Can you do that @sharaths21312, or @mrigankpawagi?

**Comment by mrigankpawagi** [comment]
I have merge access, but a few changes/fixed need to be made.

**Review by mrigankpawagi — CHANGES_REQUESTED** [review]
- The footer looks good, but the 1200px wrapper is not in place.
- It seems that max-width: 1200px has been removed from <main>
- The footer seems broken on pages except Home
- We shall keep the existing About text for now. Let us work on it and publish a polished version in some time.

**Comment by NaveenMaurya749** [comment]
It should be good to go now... that is, at least the footer.
image

**Comment by mrigankpawagi** [comment]
I am closing this PR as it has been incorporated in #10.

**Pull request closed without merging**
