### PR TITLE
Resolves #18 - Using header-component for navbar

### LINKED ISSUE #18: Use footerinclude.js to generate the navbar for all pages
Currently, the navbar has mixed implementation where in some pages have the navbar included as static HTML and some newer pages use `footerinclude.js` to generate the navbar. Every page should use `footerinclude.js` so that making changes to the navbar is easier and does not involve manually checking every HTML file for updating the navbar element.

Current Status of Pages using `footerinclude.js`:
- [ ] `/index.html`
- [ ] `/about/index.html`
- [ ] `/learn/index.html`
- [ ] `/events/index.html`
- [x] `/pages/launch/index.html`
- [ ] `/pages/paradox/index.html` 
- [ ] `/pages/projects/index.html`

It is also important to keep in mind that while adding a navbar element, absolute paths from the website root (e.g. `/pages/launch/index.html`) should be used instead of relative paths (e.g. `../pages/launch/index.html`). Using a `/` in front of the path will ensure that it is the path from the website root.

### PR DESCRIPTION
**Pull request by TheUltimateKeval**
Removes static HTML used for navbar with the `<header-component>` implemented by `footerinclude.js`.

### CODE REVIEW

**Comment by TheUltimateKeval** [comment]
I thought so but I seem to have missed one page - `/events/index.html`. Will later add a commit addressing this.

**Comment by TheUltimateKeval** [comment]
There is an inconsistency in the navbar implemented in `footerinclude.js`.
```html
<nav>
<div class="nav-box">
  <a href="/" class="headerLogo">
    <img src="/img/Logo_transparent.png" alt="databased logo"/>
  </a>

  <a href="/about" class="nav-list-link">About</a>
  <!-- <a href="/learn" class="nav-list-link">Learn</a> -->
  <a href="/events" class="nav-list-link">Events</a>
  <a href="https://databasediisc.blogspot.com/" class="nav-list-link">Blog</a>
  <a href="/pages/projects" class="nav-list-link">Projects</a>
  <a href="#contact" class="nav-list-link">Contact</a>

  <a id="nav-hamburger" data-state="inactive">
    <span></span><span></span><span></span>
    <p>&times;</p>
  </a>
</div>
</nav>
<div id="mobileMenu">
  <a href="#about">About</a>
  <!-- <a href="/learn">Learn</a> -->
  <a href="#events">Events</a>
  <a href="https://databasediisc.blogspot.com/">Blog</a>
  <a href="/pages/projects">Projects</a>
  <a href="#contact">Contact</a>
</div>
```

In the normal navbar, "About" and "Events" point to the dedicated pages `/about/index.html` and `/events/index.html`. But in the mobile navbar, they point to their sections on the home page. I need confirmation on where they should point so that I can make them consistent for both normal and mobile navbar.

Also, the URLs which point to sections don't use root paths and hence don't work on any page other than the home page. I plan to fix both these issues in another commit after I get confirmation on the above.

**Comment by mrigankpawagi** [comment]
The normal navbar has the correct links. Thanks for pointing out these. I remember fixing it on some pages but it was definitely not consistent at that time.

**Comment by TheUltimateKeval** [comment]
@mrigankpawagi I think this PR is ready for merging now. Kindly review the changes.

**Review by mrigankpawagi — APPROVED** [review]
LGTM. Thanks a lot!

**Pull request merged**
