### PR TITLE
Add Ideathon page to the Events page

### PR DESCRIPTION
**Pull request by kevalpithadiya**
- Added previously missing footer to the Ideathon page
- Added winners to the Ideathon page
- Implemented slider-like major event display on the event page
  - Cycles through to next event every 5 second
  - Can also be navigated with the use of buttons provided
- Added Ideathon to the major event display

### CODE REVIEW

**Review by mrigankpawagi — APPROVED** [review]
Excellent. Neat. Some suggestions for the future (please add these to an issue to keep track).

1. Add something like [this](https://github.com/marketplace/actions/deploy-pr-preview) to make it easier to review PRs (currently I have to pull and start a local server).
2. The "Main" events section in events should be automated, in the sense that updating it should not require modification in the code. This means you load it dynamically from the Airtable. On that note, _why are events not updated?_ It is useless if it is not updated.
3. Make/implement a "template" for adding new pages to `pages/`, so that future maintainers have an easy time (and you too can do things much faster).

We are at a stage where we can imagine things to scale upwards, and so it is worthwhile to invest time into improving our pipeline.

**Comment by kevalpithadiya** [comment]
1. Automating this would be a great QoL improvement. Will definitely look into it asap.

2. I suppose that can be done without too many changes needing to be made. My general concern regarding this is the formatting of the accompanying text and how to deal with rendering the event if in future we need more customization. We will add the events to the already existing events table soon.

3. That is a good idea but currently the code shared between files is quite messy so it will take some time to isolate and unify all the different components required. I will try to set up a template page with all the previously designed UI elements and compile together a CSS file with generic names so that they can be copied and used wherever needed.

**Comment by mrigankpawagi** [comment]
For (2), you have to find the minimum common structure. The text formatting can be handled at the Airtable side (simply by putting HTML tags in the Airtable text!)

For (3), I will instead suggest something like an "init" script, so I run something like `./createpage.sh <name>` and it automatically creates the directories, sets up the HTML, CSS, Js files, etc.

**Comment by mrigankpawagi** [comment]
Unsubscribing from this thread... Please create an issue with the TODOs. @kevalpithadiya

**Pull request merged**
