### PR TITLE
Move Open Day page from Navbar to Events page

### PR DESCRIPTION
**Pull request by kevalpithadiya**
This PR does the following :
- Removed Open Day link from the Navbar
- Minor fix addressing missing opening `head` tag in the Events page
- Added a new section for Open Day in the previous title section of the Events page

# Preview
image

image

### CODE REVIEW

**Review by mrigankpawagi — CHANGES_REQUESTED** [review]
This looks very good. Some comments: 

1. Maybe the margins and padding in mobile view can be improved. Also that there is no right padding in the image container on desktop view is a little weird. It would probably be better to remove the top and bottom padding (instead of adding a right padding).

2. The "header" section of the page has a purple overlay which still have fixed height (`100vh`) but the header itself has overflown due to the large image-box. One can see a distinct end-of-purple line. You might want to consider alternative designs which restrict the image-box to the header (I think one should not have to scroll to see the full image-box).

3. I like the overall design but I would want to understand what plans you have about this image-box going forward... Will we have a single image box for the most recent "important" event, or will we have multiple such image-boxes in the future for all "important" events.

Let me know if you need any more explanation/help. Thanks for the PR.

**Comment by kevalpithadiya** [comment]
> This looks very good. Some comments:
> 
>     1. Maybe the margins and padding in mobile view can be improved. Also that there is no right padding in the image container on desktop view is a little weird. It would probably be better to remove the top and bottom padding (instead of adding a right padding). In the mobile view, the horizontal and vertical padding should be equal in my opinion.
> 
>     2. The "header" section of the page has a purple overlay which still have fixed height (`100vh`) but the header itself has overflown due to the large image-box. One can see a distinct end-of-purple line. You might want to consider alternative designs which restrict the image-box to the header (I think one should not have to scroll to see the full image-box).
> 
>     3. I like the overall design but I would want to understand what plans you have about this image-box going forward... Will we have a single image box for the most recent "important" event, or will we have multiple such image-boxes in the future for all "important" events.
> 
> 
> Let me know if you need any more explanation/help. Thanks for the PR.

1. The padding issue is just an oversight, I'll rectify that right away.

2. This issue is difficult to deal with because the scrolling background animation is hard-coded in `common.js` and shared between all pages. My opinion is to do away with the animation entirely since it also causes significant performance issues while scrolling. I will see if there is an alternate method to implement such an effect.

I do agree with your suggestion regarding restricting image-box to the screen. I will try adjusting the font-sizing and other things to see if we can restrict the image-box.

3. My plan for it is that in the future we can have a slideshow like element which will cycle through multiple "important" events. It's better to have this than putting Open Day along with CP sessions. In more distant future, I suppose we will need to have a main events page for current year + last year (?) and then have separate pages for past years.

**Comment by kevalpithadiya** [comment]
I think this can be merged now. The scrolling effect will be addressed in a separate issue / PR in the future.

**Review by mrigankpawagi — APPROVED** [review]
Looks OK now. Maybe it can be made neater for wide landscape and wide portrait screens.

**Pull request merged**
