### PR TITLE
Fix root-based URL referencing

### PR DESCRIPTION
**Pull request by kevalpithadiya**
## The Problem
Until now, the website was using a mix of relative and absolute (root-based) URL addresses for different resources. Relative URLs are desirable because then they are not dependent of the site root URL (i.e. if it is directly on the domain `https://databased.csa.iisc.ac.in/index.html` or if it is at some path `https://databased.csa.iisc.ac.in/pr-preview/pr-30/index.html`. However, absolute URLs were being used as in the header component since the same static HTML was to be inserted in all pages and hence relative URLs could not be used. But this meant that the website only works if it is hosted at the top level.

## The Fix
The [base](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/base) HTML tag can be used to specify the address from which any relative addresses in the HTML page are evaluated from. This PR adds the base tag to all the HTML pages which points to the site root using a relative address itself (e.g., if the page is at `/pages/ideathon/index.html`, the base tag has `href="../../"`) and modified all site URLs in a page to be root-relative.

The header component can now simply have relative addresses w.r.t. the site root and the same HTML inserted in any page will work without issue.

## New Problem
This however had compatibility issues with the existing implementation of the member profile pages which existed at the artificial `/member/<username>` URL by relying on being redirected to the `404.html` and then replicating a dynamic site behavior through a script. This is a very janky way of implementing the profile pages and causes trouble since the HTML page is `/404.html` while the URL path is `/member/<username>` and the browser misinterprets the base tag reference.

Since this was a very janky implementation, I've instead created a dedicated page `/about/member.html` which instead loads and renders a member profile based on the `username` URL query parameter (e.g., `/about/member.html?username=kevalp`).

## Things to keep in mind
- All new pages must have the base tag correctly pointing to the site root with a relative address.
- Enforce all site URLs within HTML to be root-relative.
- The base tag only works for URLs within the HTML.
- Any relative URLs used in CSS and JS will be resolved w.r.t. the file itself.
- Any JS which inserts DOM elements into an HTML page must ensure any URLs in the HTML are root-relative.

**NOTE: This fix is necessary because this a major bug and must be fixed to add the Deploy PR Preview GitHub Action**

### CODE REVIEW

**Comment by mrigankpawagi** [comment]
This is a good thing to do. I will eyeball all the pages to make sure the referencing is working fine. 

For the change to `member.html?user=<username>`: the current implementation with 404 is much more complicated than your update, but we (or maybe I) did that intentionally purely for the visual appeal and the convenience associated with `/member/<username>` (compared to which, passing a GET param to a `.html` page is too much to type from memory and also _looks_ too verbose).

Why not instead set the `base` tag dynamically? [Check this.](https://stackoverflow.com/questions/3494954/how-do-i-set-a-pages-base-href-in-javascript)

**Comment by kevalpithadiya** [comment]
I agree the `/member/<username>` implementation does look better but at the end it is something which should be done server side. You cannot accurately determine if it is actually the correct path. For instance, with the existing implementation, `https://databased.csa.iisc.ac.in/abc/member/kevalp` also works.

Our goal with a static website should be to keep it root agnostic (given we want to deploy the site at arbitrary paths and not just at the hostname). It all boils down to being able to determine the site root from each page, for which there is no simple method. The simplest solution for us is enforcing the `base` tag with a relative `href` attribute as all the necessary information for correct routing is within the static site code.

The dynamic solutions suggested on the SO post are all useless since `document.location.hostname` is only the hostname part of the URL which is domain or IP address. I think they are trying to address the issue of site being hosted only at multiple domains, and not at any arbitrary path.

Regarding the new `member.html?username=<username>` format, I do agree it is quite verbose, but it is in line with what the general Web and URL spec was designed for. I highly doubt if anyone will be trying to reach a profile on our website from memory. Although I am open to suggestions on how it can be made a little more concise. Perhaps,
- We can move it to `/member/index.html` so the shorthand `/member/?username=<username>` works.
- We can change the query parameter to just be `u=<username>` instead of `username=<username>`.

**Comment by mrigankpawagi** [comment]
Good catch. I think one could alternatively fix the logic in 404.html so that `/abc/memeber/<...>` goes to the actual 404!

I will have to look more into how `<base>` works to talk about what could be done...

The current solution (and your fix) still has the fundamental problem of being dynamic pages! An ideal solution would be to use a GitHub build action to create static pages for each user (like how jekyll does it). That would mean that people have to make a PR to this repo instead of filling that simple Airtable form (for those who are already registered, one can write a script to automatically port those users). This would be more effort from your end though... but once done it will be infinitely better for our SEO (currently the member pages don't even exist for crawlers!).

**Comment by kevalpithadiya** [comment]
> Good catch. I think one could alternatively fix the logic in 404.html so that /abc/memeber/<...> goes to the actual 404!

I am doubtful about being able to fix the logic since our only reliable way of determining the site root is through the relative root path in the `base` tag. This in turn relies on the fact that the page being served is in fact located at that path in the site tree. For example, the page `/pages/ideathon/[index.html]` will always be served at `<site_root>/pages/ideathon/[index.html]` and hence the relative root path `../../` will always point to `<site_root>`.

The `404.html` page is a problem since it can be served at any non-existent path. For example, the path `<site_root>/member/abcd` will serve the `404.html` page. But since the base is fixed in the HTML to be `./`, it would point to `<site_root>/member/abcd` itself.  If we change it to be `../../`, it will point to the site root for the above URL but will fail for some other URL.

This itself raises the question on how the `404.html` page should behave after the proposed fix but that can be dealt with later since the `404.html` page is not something we are serving as actual information / content. But if we use it show the member profiles, it will cause the header links to be broken because of the incorrect base reference.

_I have done quite some digging on this already over a few weeks before deciding this was a good solution. But do see if you can figure out something better._

> The current solution (and your fix) still has the fundamental problem of being dynamic pages! An ideal solution would be to use a GitHub build action to create static pages for each user (like how jekyll does it). That would mean that people have to make a PR to this repo instead of filling that simple Airtable form (for those who are already registered, one can write a script to automatically port those users). This would be more effort from your end though... but once done it will be infinitely better for our SEO (currently the member pages don't even exist for crawlers!).

Yes, the pages are indeed dynamic. By `dynamic site` in the earlier comments, I meant to say server-side managed sites which could correctly determine responses to URL paths. Regarding generating static pages, one could possibly setup GitHub Actions, **IF** we have any major plans to expand the member profiles. Currently, they serve to only be reachable from the about page.

**Comment by kevalpithadiya** [comment]
This post [What are the recommendations for html base tag?](https://stackoverflow.com/questions/1889076/what-are-the-recommendations-for-html-base-tag) on StackOverflow lists some pitfalls of using the `base` tag which I might have overseen.

Some of the responses mention incompatibility with web crawlers but those comments are very old and present-day crawlers are probably a lot more sophisticated. I will go through the post in detail later when I get the time.

**Comment by kevalpithadiya** [comment]
The only plausible drawback of using the base tag seems to be an issue of some JavaScript libraries may not support it. The lack of support would technically be a bug in the library. I don't think this poses much of a challenge compared to all the issues this solves.

I think this should be merged now so that I can proceed with adding other features.

**Comment by mrigankpawagi** [comment]
If nothing has broken, feel free to merge. But I will suggest that you extract the changes related to member pages to another PR and discuss more. One way to go forward (for now) would be to redirect the original 404-based pages to your new parameter-based pages.

>  IF we have any major plans to expand the member profiles.

Frankly, I am not sure if we should even keep these profiles because (1) nobody asked for it, (2) nobody maintains it, and (3) they are not serving any purpose besides links to people's GitHub/LinkedIn (ideally these can be placed next to the member photos on About page and we can even totally do away with the member pages). 

Member pages are _vestigial_ at best. The story behind adding these pages is that we wanted to maintain some sort of contributor profile which displayed what ever member has been doing, as well as (drumroll!) their performance in our weekly problem solving sessions (some scoring system + leaderboard yada yada).

**Pull request merged**
